Repository leobrod44/Mini-Capstone, pull requests merged in 2024-04, with the labels that each got.

#312 US6-T4 financial status pay rent backend
  mini-cap/src/backend/FinancialHandler.js
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/components/FinancialDetails.jsx
  mini-cap/src/tests/FinancialHandler.test.js
  mini-cap/src/tests/PropertyCondoHandler.test.js
Labels: backend

#321 US12-T2 generate financial report
  mini-cap/package-lock.json
  mini-cap/package.json
  mini-cap/src/backend/FinancialHandler.js
  mini-cap/src/backend/FinancialReportHandler.js
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/tests/FinancialHandler.test.js
  mini-cap/src/tests/FinancialReportHandler.test.js
Labels: backend

#315 310 us15 create notification popup
  mini-cap/src/components/Notification.jsx
  mini-cap/src/styling/Header.css
  mini-cap/src/styling/Notification.css
  mini-cap/src/tests/Notification.test.js
Labels: task, frontend

#327 US12-T2 generate financial report (button styling)
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/styling/CondoDetails.css
Labels: frontend

#332 328 us6 i want the financial system to present status hints for rent payments
  mini-cap/src/components/FinancialDetails.jsx
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/styling/FinancialDetails.css
  mini-cap/src/tests/FinancialDetails.test.js
Labels: task, frontend

#338 Us13 add facility implementation
  mini-cap/src/App.js
  mini-cap/src/backend/FacilityHandler.js
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/components/FacilityForm.jsx
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/pages/PropertyDetailsPage.jsx
  mini-cap/src/pages/PropertyFacilities.jsx
  mini-cap/src/styling/PropertyDetailsPage.css
  mini-cap/src/styling/PropertyFacilities.css
Labels: task, frontend, backend

#307 Us7 view request bug fixes
  mini-cap/src/backend/RequestHandler.js
  mini-cap/src/components/CondoRequestsView.jsx
Labels: bug, frontend

#343 Added pagination to the Property Facilities page to declutter the layout
  mini-cap/src/pages/PropertyFacilities.jsx
Labels: frontend

#341 Us13 Reservation and calendar page #340 #304 #322
  mini-cap/src/backend/FacilityHandler.js
  mini-cap/src/backend/ImageHandler.js
  mini-cap/src/components/FacilityComponent.jsx
  mini-cap/src/components/ReservationComponent.jsx
  mini-cap/src/pages/CalendarPage.jsx
  mini-cap/src/pages/Reservations.jsx
  mini-cap/src/styling/Calendar.css
  mini-cap/src/styling/FacilityComponent.css
  mini-cap/src/styling/Reservations.css
  mini-cap/src/tests/FacilityComponent.test.js
  mini-cap/src/tests/ReservationComponent.test.js
  mini-cap/src/tests/ReservationsPage.test.js
Labels: frontend

#362 360 pay rent option is showing up for management companies
  mini-cap/src/components/FinancialDetails.jsx
  mini-cap/src/tests/FinancialDetails.test.js
Labels: bug

#368 333 bug property id is being displayed on condo component
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/pages/Dashboard.jsx
Labels: bug

#374 Fix advance button requests
  mini-cap/src/backend/RequestHandler.js
  mini-cap/src/components/CondoRequestsView.jsx
  mini-cap/src/pages/CondoDetails.jsx
Labels: bug
