Repository leobrod44/Mini-Capstone, pull requests merged in 2024-03, with the labels that each got.

#172 Fixed bug #169: condo pictures not displaying in MGMT dashboard
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/pages/PropertyDetailsPage.jsx
Labels: bug

#195 Us5 populate condo details
  mini-cap/src/App.js
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/backend/UserHandler.js
  mini-cap/src/components/CondoComponent.jsx
  mini-cap/src/components/CondoMGMTComponent.jsx
  mini-cap/src/components/DeleteModal.jsx
  mini-cap/src/pages/AddCondoForm.jsx
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/pages/Dashboard.jsx
Labels: frontend, backend

#200 Us11 hide send key button
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/components/CondoMGMTComponent.jsx
Labels: frontend, backend

#207 Us8 refactoring property form
  mini-cap/src/components/AddCondoFormComponent.jsx
  mini-cap/src/pages/AddCondoForm.jsx
  mini-cap/src/pages/PropertyForm.jsx
  mini-cap/src/styling/propertyform.css
  mini-cap/src/tests/AddCondoFormComponent.test.js
  mini-cap/src/tests/PropertyForm.test.js
Labels: enhancement

#211 Us7 t3 condo requests view
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/backend/RequestHandler.js
  mini-cap/src/components/CondoRequestsView.jsx
  mini-cap/src/pages/CondoDetails.jsx
  mini-cap/src/styling/CondoDetails.css
  mini-cap/src/styling/CondoRequestsView.css
Labels: frontend

#220 Updated RequestHandler.js syntax error
  mini-cap/src/backend/RequestHandler.js
Labels: bug

#223 US16-T1-T2 assign request to worker
  mini-cap/src/backend/PropertyHandler.js
  mini-cap/src/backend/RequestHandler.js
Labels: backend

#224 US6-T1 calculate condo fee logic
  mini-cap/src/backend/PropertyHandler.js
Labels: backend

#227 Modifying property and condo creation functions for requests and workers model change
  mini-cap/src/backend/PropertyHandler.js
Labels: backend

#232 HOTFIX: update PropertyHandler.js calculateCondoFees
  mini-cap/src/backend/PropertyHandler.js
Labels: bug

#256 HOTFIX: fix issue with refactor not properly setting condo parking and locker number #257
  mini-cap/src/backend/PropertyHandler.js
Labels: bug

#251 US7 made condo requests only available for owners #197
  mini-cap/src/pages/CondoDetails.jsx
Labels: bug, frontend

#264 issue #245 adding documentation to code written in sprint 2
  mini-cap/src/components/CondoComponent.jsx
  mini-cap/src/components/CondoMGMTComponent.jsx
  mini-cap/src/components/PropertyComponent.jsx
Labels: documentation

#268 Us8 removing mini condo form
  mini-cap/src/pages/PropertyForm.jsx
  mini-cap/src/tests/AddCondoFormComponent.test.js
  mini-cap/src/tests/PropertyDetailsPage.test.js
  mini-cap/src/tests/PropertyForm.test.js
Labels: task

#274 US10 - Add Tests and Documentation to Edit Property Closes #113
  mini-cap/src/components/EditPropertyComponent.jsx
  mini-cap/src/pages/PropertyDetailsPage.jsx
  mini-cap/src/tests/EditPropertyComponent.test.js
  mini-cap/src/tests/PropertyDetailsPage.test.js
Labels: documentation, tests

#276 Us15 fixes for request integration
  mini-cap/src/backend/Constants.js
  mini-cap/src/backend/RequestHandler.js
  mini-cap/src/components/RequestForm.jsx
  mini-cap/src/pages/CondoDetails.jsx
Labels: frontend, backend

#271 Update getCondoFees return values for frontend compatibility #269
  mini-cap/src/backend/PropertyHandler.js
Labels: backend

#277 Linking financial details frontend with backend
  mini-cap/src/components/FinancialDetails.jsx
  mini-cap/src/pages/CondoDetails.jsx
Labels: documentation, frontend, backend

#283 Test coverage for condoMGMTComponent #281
  mini-cap/src/tests/CondoMGMTComponent.test.js
Labels: tests

#284 Write edit and modify condo and property function tests
  mini-cap/src/tests/PropertyCondoHandler.test.js
Labels: backend

#298 Create Request button Bug Fix
  mini-cap/src/pages/CondoDetails.jsx
Labels: bug
